/**
 * Copyright (c) 2011 RAAXXO
 * 
 * This file is part of Dinosaur Island.
 * 
 */
package commands.responses;

/**
 * <b>Overview</b><br>
 * <p>
 * The Response class is an object that represents the server response
 * to a client requests. 
 *
 * <b>Responsibilities</b><br>
 * <p>
 * It stores information about the server response: its stored information
 * depends strictly by the type of response generated. See subclasses
 * for futher information.
 * </p>
 *
 * <b>Collaborators</b><br>
 * <p>
 * A {@link Response} object can be generated by a {@link ResponseFactory} that
 * can build a response from a string representing the server response.<br>
 * </p>
 *
 * @see ResponseFactory
 * 
 * @author	RAA
 * @version 1.0
 *
 */
public abstract class Response {
	
	protected boolean outcomePositive;
	
	/** 
	 * The method isOutcomePositive returns if the response of the server
	 * is a positive response or a negative response of a client requests.
	 *
	 * @return true if the response is a positive response of a client request, false if it isn't
	 *
	 * @see		ResponseFactory
	 * 
	 */
	public boolean isOutcomePositive() {
		return outcomePositive;
	}

	/** 
	 * The method isOutcomePositive returns if the response of the server
	 * is a positive response or a negative response of a client requests.
	 *
	 * @return true if the response is a positive response of a client request, false if it isn't
	 *
	 * @see		ResponseFactory
	 * 
	 */
	/** 
	 * The method setOutcomePositive sets if the response of the server
	 * is a positive response or a negative response of a client requests.
	 *
	 * @param theOutcomePositive is a boolean value representing the positivity of the response    
	 *
	 * @see		ResponseFactory
	 * 
	 */
	public void setOutcomePositive(boolean theOutcomePositive) {
		outcomePositive = theOutcomePositive;
	}
	
	Response() {}

}